apiVersion: v1
kind: ConfigMap
metadata:
  name: autotune-config
data:
  cluster_type: "kubernetes"
  k8s_type: "docker"
  auth_type: ""
  auth_token: ""
  monitoring_agent: "prometheus"
  monitoring_service: ""
  monitoring_agent_endpoint: ""
  logging_level: "info"

