apiVersion: v1
kind: ConfigMap
metadata:
  name: autotune-config
data:
  cluster_type: "kubernetes"
  k8s_type: "openshift"
  auth_type: ""
  auth_token: ""
  monitoring_agent: "prometheus"
  monitoring_service: "prometheus-k8s"
  monitoring_agent_endpoint: ""
  root_logging_level: "info"
  logging_level: "info"
