apiVersion: "recommender.com/v1"
kind: "KruizeMetadataProfile"
metadata:
  name: "cluster-metadata-local-monitoring"
profile_version: 1.0
k8s_type: openshift
datasource: prometheus
query_variables:

- name: namespacesForAdditionalLabel
  datasource: prometheus
  value_type: "double"
  kubernetes_object: "namespace"
  aggregation_functions:
  - function: sum
    query: 'sum by (namespace) (avg_over_time(kube_namespace_status_phase{namespace!="" ADDITIONAL_LABEL}[$MEASUREMENT_DURATION_IN_HOUR$h]))'

- name: workloadsForAdditionalLabel
  datasource: prometheus
  value_type: "double"
  kubernetes_object: "container"
  aggregation_functions:
  - function: sum
    query: 'sum by (namespace, workload, workload_type) (avg_over_time(namespace_workload_pod:kube_pod_owner:relabel{workload!="" ADDITIONAL_LABEL}[$MEASUREMENT_DURATION_IN_HOUR$h]))'

- name: containersForAdditionalLabel
  datasource: prometheus
  value_type: "double"
  kubernetes_object: "container"
  aggregation_functions:
  - function: sum
    query: 'sum by (container, image, workload, workload_type, namespace) (avg_over_time(kube_pod_container_info{container!="" ADDITIONAL_LABEL}[$MEASUREMENT_DURATION_IN_HOUR$h]) * on (pod, namespace) group_left(workload, workload_type) avg_over_time(namespace_workload_pod:kube_pod_owner:relabel{workload!="" ADDITIONAL_LABEL}[$MEASUREMENT_DURATION_IN_HOUR$h]))'
