apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "hotspot"
layer_name: hotspot
layer_level: 1
details: hotspot tunables
layer_presence:
  queries:
  - datasource: prometheus
    query: 'jvm_memory_used_bytes{area="heap",}'
    key: pod
tunables:
- name: MaxInlineLevel
  description: 'maximum number of nested calls that are inlined. Default is 9'
  value_type: integer
  upper_bound: '50'
  lower_bound: '9'
  queries:
  - datasource: 'prometheus'
    query: 'jvm_memory_used_bytes{area="heap", $CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
  step: 1
  slo_class:
  - response_time
  - throughput
