apiVersion: "recommender.com/v1beta1"
kind: "AutotuneQueryVariable"
metadata:
  name: "minikube"
  namespace: "monitoring"
query_variables:
  - name: '$POD_LABEL$'
    value: 'pod_name'
  - name: '$CONTAINER_LABEL$'
    value: 'container'

