name: Test on Pull Request 

# Controls when the action will run. 
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'examples/**'
      - 'extensions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout autotune
        uses: actions/checkout@v2
        with:
          repository: kruize/autotune
          ref: integration-channel-RM-EM
          path: autotune

      - name: Checkout benchmarks
        uses: actions/checkout@v2
        with:
          repository: kruize/benchmarks
          path: benchmarks

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - name: Start minikube
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

      - name: Build autotune
        run: |
          echo Build autotune
          cd autotune
          ./build.sh -i autotune_operator:int-test -o autotune_optuna:int-test
          docker images | grep autotune     

      - name: Install Prometheus on minikube
        run: |
          echo Install Prometheus on minikube
          cd autotune/scripts
          ./prometheus_on_minikube.sh -as

      - name: Update Always to ImagePullPolicy in autotune deployment
        run: |
          echo Update Always to ImagePullPolicy in autotune deployment
          cd autotune
          cp ./manifests/autotune-operator-deployment.yaml_template ./manifests/autotune-operator-deployment.yaml_template.old
          sed -e "s/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g" ./manifests/autotune-operator-deployment.yaml_template.old > ./manifests/autotune-operator-deployment.yaml_template
          echo "***************************************************************"
          cat ./manifests/autotune-operator-deployment.yaml_template
          echo "***************************************************************"

      - name: Run tests
        run: |
          echo Running Dependency Analyzer tests
          cd autotune/tests
          ./test_autotune.sh -c minikube -i autotune_operator:int-test -o autotune_optuna:int-test --tctype=functional --testmodule=da --resultsdir=${GITHUB_WORKSPACE} -r ${GITHUB_WORKSPACE}/benchmarks

          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf autotune_test_results.tar autotune_test_results
          ls
